### ISSUE TITLE
Client fails to bind to port when using autostart

### ISSUE THREAD

**Issue by ddgenome** [atomist/automation-client-ts#206]
Automation clients sometimes fail to bind to the port when using the autostart package script. This may be due to the asynchronous shutdown not releasing the port until after the new client tries to bind to it.

**Comment by ddgenome** [comment]
Here are the relevant package scripts:

```
  "autostart": "npm-run-all --print-label --parallel watch:compile watch",
  "start": "atomist start --no-install --no-compile",
  "watch:compile": "tsc --project . --watch",
  "watch": "supervisor --watch build --quiet --exec npm -- run start",
```

What appears to be happening is that the compilation and client start, the client binds to the port, the compilation completes, supervisor sees files under the build directory have changed, it sends the running client SIGTERM which initiates shutdown, it starts the new client up, and the new client tries to connect to the port before the old client has released its connection to it. Here's the relevant log:

```
[watch        ] 2018-01-24T13:46:16.765Z [m:91636] [info ] Registering @atomist/automation-seed@0.4.1 with Atomist at 'https://automation.atomist.com/registration': {"api_version":"1","name":"@atomist/automation-seed","version":"0.4.1","policy":{"name":"ephemeral"},"team_ids":["T095SFFBK"],"commands":[{"name":"HelloWorld","description":"sends a hello back to the channel","tags":["hello"],"intent":["hello world"],"auto_submit":false,"parameters":[{"name":"name","pattern":"^.+$","description":"name of person to say hello to","required":true,"displayable":true,"max_length":100,"min_length":1,"valid_input":"a single line of text","display_name":"Name"}],"mapped_parameters":[{"name":"slackUser","uri":"atomist://slack/user_name","required":true}],"secrets":[]}],"events":[{"subscription":"subscription PushWithRepo { Push { after { sha } repo { channels { name } } }}","secrets":[]}],"ingesters":[],"metadata":{"labels":{"atomist.description":"Atomist automation seed project","atomist.license":"Apache-2.0","atomist.author":"Atomist","atomist.homepage":"https://github.com/atomist/automation-seed-ts#readme","atomist.client":"@atomist/automation-client#0.6.4","atomist.git.sha":"bcdfef811412a4bd044c76f1515915f697d3ad7a","atomist.git.branch":"master","atomist.git.repository":"git@github.com:atomist/automation-seed-ts.git","atomist.system.hostname":"sfz-mbp.lan","atomist.system.type":"Darwin","atomist.system.release":"15.6.0","atomist.system.platform":"darwin"}}}
[watch        ] 2018-01-24T13:46:16.800Z [m:91636] [error] {"errno":"EADDRINUSE","code":"EADDRINUSE","syscall":"listen","address":"::","port":2866,"name":"Error","message":"listen EADDRINUSE :::2866","stack":"Error: listen EADDRINUSE :::2866\n    at Object._errnoException (util.js:1003:13)\n    at _exceptionWithHostPort (util.js:1024:20)\n    at Server.setupListenHandle (net.js:1366:14)\n    at Server._listen2 (/Users/dd/develop/atomist/automation-seed-ts/node_modules/async-listener/index.js:96:23)\n    at listenInCluster (net.js:1407:12)\n    at Server.listen (net.js:1495:7)\n    at Function.listen (/Users/dd/develop/atomist/automation-seed-ts/node_modules/express/lib/application.js:618:24)\n    at new ExpressServer (/Users/dd/develop/atomist/automation-seed-ts/node_modules/@atomist/automation-client/internal/transport/express/ExpressServer.js:111:13)\n    at AutomationClient.runHttp (/Users/dd/develop/atomist/automation-seed-ts/node_modules/@atomist/automation-client/automationClient.js:176:31)\n    at AutomationClient.run (/Users/dd/develop/atomist/automation-seed-ts/node_modules/@atomist/automation-client/automationClient.js:73:42)"}
[watch        ] 2018-01-24T13:46:19.747Z [m:91636] [info ] Registration successful: {"url":"wss://automation.atomist.com/registration/9cb12847-7e48-4f0a-b4f8-43a260254261","jwt":"9cb12847-7e48-4f0a-b4f8-43a260254261","endpoints":[],"name":"@atomist/automation-seed","version":"0.4.1"}
[watch        ] 2018-01-24T13:46:19.750Z [m:91636] [info ] Opening WebSocket connection
[watch        ] 2018-01-24T13:46:19.877Z [m:91636] [info ] WebSocket connection established. Listening for incoming messages
```

**Comment by ddgenome** [comment]
I'm finding that autostart is leaving parentless node processes around.

**Comment by ddgenome** [comment]
Customer saw on macOS High Sierra that hitting Ctrl-C did not kill parent npm process for `npm run autostart`, leaving client attached and command and event handlers available.

**Comment by ddgenome** [comment]
It looks like at least part of the problem is that `atomist start` does not kill the `node .../start.client.js` process it has created when it gets killed.

**Comment by ddgenome** [comment]
Some resources:

-   https://www.hacksparrow.com/difference-between-spawn-and-exec-of-node-js-child_process.html
-   https://nodejs.org/api/child_process.html
-   https://medium.freecodecamp.org/node-js-child-processes-everything-you-need-to-know-e69498fe970a
-   https://dzone.com/articles/understanding-execfile-spawn-exec-and-fork-in-node

**Comment by ddgenome** [comment]
Useful monitoring commands

Get the process group ID from the first command and use it in the second.

```
$ ps -O ppid,pgid,start | awk 'NR == 1 || (/automation-seed-ts/ && !/awk/)'
$ ps -O ppid,pgid,start | awk 'NR == 1 || (/PGID/ && !/awk/)'
```

**Comment by ddgenome** [comment]
[supervisor](https://github.com/petruisfan/node-supervisor) leaves reaps its children but orphans its grandchildren. Switching to [ts-node](https://github.com/TypeStrong/ts-node) and calling it directly with [nodemon](https://github.com/remy/nodemon), which reaps its children and grandchildren, seems to have resolved this issue.

Since this really has more to do with clients than this client library, it was fixed in the [automation-seed](https://github.com/atomist/automation-seed-ts) commit atomist/automation-seed-ts@d22afb024a1079617ac18289f6e054cc9a026449.
