### ISSUE TITLE
Error starting automation client should not result in registration

### ISSUE THREAD

**Issue by donovanmuller** [atomist/automation-client-ts#39]
If there is an error starting up the automation client (port already in use for example), then registration should fail:

```console
Loading GraphQL Introspection from file: node_modules/@atomist/automation-client/graph/schema.cortex.json...
Generated file written to /.../atomist/apiman-automation/src/typings/types.d.ts
2017-10-23T05:11:52.827Z [error] WARNING: No configurations found in configuration directory:/.../atomist/apiman-automation/config
2017-10-23T05:11:52.828Z [error] WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
2017-10-23T05:11:52.879Z [debug] Using configuration from 'build/src/atomist.config.js': {"name":"apiman-automation","version":"0.1.0","teamIds":"T6AMU844U","token":"5**************************************f","http":{"enabled":true,"auth":{"basic":{"enabled":false},"bearer":{"enabled":false}}}}
2017-10-23T05:11:52.881Z [info ] Starting Atomist automation client for apiman-automation@0.1.0
2017-10-23T05:11:52.883Z [info ] Registering apiman-automation@0.1.0 with Atomist at 'https://automation.atomist.com/registration': {"name":"apiman-automation","version":"0.1.0","team_ids":["T6AMU844U"],"commands":[],"events":[]}

2017-10-23T05:11:52.927Z [error] {"code":"EADDRINUSE","errno":"EADDRINUSE","syscall":"listen","address":"::","port":2866,"name":"Error","message":"listen EADDRINUSE :::2866","stack":"Error: listen EADDRINUSE :::2866\n    at Object._errnoException (util.js:1022:11)\n    at _exceptionWithHostPort (util.js:1045:20)\n    at Server.setupListenHandle (net.js:1330:14)\n    at Server._listen2 (/.../atomist/apiman-automation/node_modules/async-listener/index.js:85:23)\n    at listenInCluster (net.js:1378:12)\n    at Server.listen (net.js:1478:7)\n    at Function.listen (/.../atomist/apiman-automation/node_modules/express/lib/application.js:618:24)\n    at new ExpressServer (/.../atomist/apiman-automation/node_modules/@atomist/automation-client/internal/transport/express/ExpressServer.js:140:13)\n    at AutomationClient.runHttp (/...t/atomist/apiman-automation/node_modules/@atomist/automation-client/automationClient.js:144:31)\n    at AutomationClient.run (/.../atomist/apiman-automation/node_modules/@atomist/automation-client/automationClient.js:58:34)"

2017-10-23T05:11:55.224Z [info ] Registration successful: {"url":"w****************************************************************************0","jwt":"c**********************************0","name":"apiman-automation","version":"0.1.0"}
2017-10-23T05:11:55.225Z [info ] Opening WebSocket connection
2017-10-23T05:11:56.447Z [info ] WebSocket connection established. Listening for incoming messages
```

Not sure if this is expected or not?

**Comment by cdupuis** [comment]
For now this is actually expected; or better that's the way it behaves which I'm not sure it is ok. Technically the automation-client doesn't require the local http server to be up and running. So I'm not sure we should fail the registration or startup only when the http server can't start.

WDYT, @donovanmuller?

**Comment by donovanmuller** [comment]
It's not a major issue for me. 

I guess the thinking was based on how other frameworks (Spring Boot for example) handle this and just to avoid any misconceptions/confusion that if an app is running that all interfaces are in a working state, not partially available. I.e. the above app could accept commands/events but could ingest events...

**Comment by cdupuis** [comment]
We changed the behaviour of starting the web server to retry for an extended period of time and then stop. The failure won't prevent the client from starting and working.
